### ISSUE TITLE
Getting API Key

### ISSUE THREAD

**Issue by mcharudatta** [belzile/coveo-for-wordpress#1]
Hi

I am exploring your Coveo for WordPress plug-in. Which API key we have to use? From where to generate this API key? Does this plug-in support multisite crawling? If yes, how to configure that?

Charudatta M.

**Comment by belzile** [comment]
Hi,

> Does this plug-in support multisite crawling? If yes, how to configure that?

this plugin is intended to add Coveo search interfaces to a wordpress site only. Site crawling can be configured from the Coveo Search platform.

> Which API key we have to use? From where to generate this API key?

I invite you to read this documentation: https://docs.coveo.com/en/1718/manage-an-organization/manage-api-keys.
API Keys can be created/managed from the Coveo Search platform.

This plugin was an experiment I did more than 2 years ago. There might be a few things in there that need to be updated.
I have not worked for Coveo since more than 2 years: I am probably outdated as well. So if you have more question about their products: ex: how to create an API key, or how to crawl a website, I invite you to ask questions on their "stack overflow" like platform. https://connect.coveo.com/s/topic/0TO0d000000gGvZGAU/developer People from Coveo are very active on this platform, are really responsive, and will be glad to help you.

**Comment by mcharudatta** [comment]
Thank you very much for your prompt reply. We will check the shared documents and see what best we can do with Coveo search for our WordPress platform.
